### PR TITLE
remove redundant terms

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Review by VMatrix1900 — APPROVED** [review]
LGTM

**Comment by khyao78** [comment]
Hi Med, all, 

There was a mailing list thread earlier in this year on the discussion of what is "computing service".
 
https://mailarchive.ietf.org/arch/msg/cats/V6tMfRIpqIbIXHNFD54RarQOrOA/https://mailarchive.ietf.org/arch/msg/cats/V6tMfRIpqIbIXHNFD54RarQOrOA/

based on some discussion happened in IETF119 Brisbane. Please take a look. Personally, I think the definition in framework draft is a bit general. 

Best,
Kehan

**Comment by boucadair** [comment]
I got a message error when accessing the link. 

Anyway, if the existing entry in the framework is too generic, let's fix that in the framework for the sake of consistency of our CARS documents. Thanks.

**Comment by khyao78** [comment]
Hi, Med,
Sorry for copying the link twice. I think the following link is accessible. I've created a issue in CATS framework repo before, issue #90(closed now).

https://mailarchive.ietf.org/arch/msg/cats/V6tMfRIpqIbIXHNFD54RarQOrOA/

BTW, I've created a issue #5 on updating metric requirements of this document, please take a look and your sugguestion is very welcomed.

https://github.com/cats-wg/draft-ietf-cats-usecases-requirements/issues/5


Best,
Kehan

**Review by khyao78 — COMMENTED** [review]
Hi Med, 

I understand that we should avoid the same definition of terms in two documents. But I have a question that is it proper to say "This  document uses the terms defined in in {{I-D.ldbc-cats-framework}}" ? Since it seems that the order is reversed. Normally, the use cases and requirement draft is ahead of framework draft. I'm not sure if this kind of description is appropriate. 

Sorry that I'm not experienced, and just for confirmation. Thanks.

Best,
Kehan

**Comment by VMatrix1900** [comment]
CATS framework will become RFC and is more appropriate place for term definition. Kehan agrees to merge the PR.

**Pull request merged**
